### ISSUE TITLE
Google QR Code API Now Defunct

### ISSUE THREAD

**Issue by robwoodgate** [bullioncapital/kinesis-pay-woocommerce#2]
The Google Chart API this plugin uses is no longer working.

A simple solution would be to switch to the [GOQR API](https://goqr.me/api/).

Alternatively, avoid a 3rd party dependency by using a jQuery library like [kjua](https://larsjung.de/kjua/)

Cheers
Rob

**Comment by andihabx** [comment]
Hi @robwoodgate ,

Thanks for your comment. The latest version 1.0.4 has been released to fix the QR code issue.

Cheers,
Andi
